modLoader = "javafml"
loaderVersion = "*"
license = "CC-BY-NC-ND-4.0"
issueTrackerURL = "https://github.com/Faboslav/friends-and-foes/issues"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = "${modDescription}"
logoFile = "icon.png"
displayURL = "https://github.com/Faboslav/friends-and-foes"

[[dependencies.${ modId }]]
modId = "forge"
mandatory = true
versionRange = "[${forgeVersion},)"

[[dependencies.${ modId }]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"

[modproperties.${ modId }]
catalogueImageIcon = "catalogue_icon.png"
catalogueBackground = "catalogue_background.png"
configuredBackground = "catalogue_background.png"